# Generated by Django 2.2.5 on 2020-03-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='room',
            field=models.CharField(default=9999999999, max_length=5),
            preserve_default=False,
        ),
    ]
